## Eager Execution

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)
tf.compat.v1.enable_eager_execution

tf.Tensor(121, shape=(), dtype=int32)


<function tensorflow.python.framework.ops.enable_eager_execution(config=None, device_policy=None, execution_mode=None)>

In [3]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


In [4]:
z.numpy()

121

## Math in tensorflow

In [5]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

In [6]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

In [7]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

In [8]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

In [9]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

In [10]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

10.0

In [11]:
x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())
print(tf.argmax(x).numpy())

1
2


In [12]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

In [13]:
print(x.dtype)

<dtype: 'int32'>


In [14]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [15]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

In [16]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

In [17]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

In [18]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

In [19]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

In [22]:
tf.reduce_mean(input_tensor=x).numpy()

2.75

In [21]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.8676406 , 0.56379414],
       [0.1830399 , 0.7946601 ],
       [0.8503088 , 0.9764669 ]], dtype=float32)

In [23]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

In [24]:
def square(x):
    return tf.multiply(x, x)

In [25]:
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())

36.0


## Tesorflow 2.0

Defining a sequestial model

In [26]:
from tensorflow import keras

In [27]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
model = Sequential()

In [29]:
model.add(Dense(13, input_dim=7, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [30]:
input = tf.keras.Input(shape=(2,))
layer1 = Dense(10, activation='relu')(input)
layer2 = Dense(10, activation='relu')(layer1)
output = Dense(1, activation='sigmoid')(layer2)
model = tf.keras.Model(inputs=input, outputs=output)

In [31]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

# MNIST digit classification using TensorFlow 2.0

In [32]:
mnist = tf.keras.datasets.mnist

In [33]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [34]:
x_train, x_test = tf.cast(x_train/255.0, tf.float32), tf.cast(x_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)

In [35]:
model = tf.keras.models.Sequential()

In [36]:
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [37]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [39]:
model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0917 - accuracy: 0.9743
Epoch 2/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0848 - accuracy: 0.9765
Epoch 3/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0786 - accuracy: 0.9779
Epoch 4/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0732 - accuracy: 0.9797
Epoch 5/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0681 - accuracy: 0.9812
Epoch 6/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0638 - accuracy: 0.9824
Epoch 7/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0598 - accuracy: 0.9838
Epoch 8/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0560 - accuracy: 0.9847
Epoch 9/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0528 - accuracy: 0.9858
Epoch 10/10
1875/1875 [==============================] - 10s 5ms/step - loss

In [40]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 3s 9ms/step - loss: 0.0843 - accuracy: 0.9742


[0.0843498632311821, 0.9742000102996826]